"""empty message

Revision ID: b0eff40d2b66
Revises: c24e73c181e4
Create Date: 2015-12-30 00:26:22.099761

"""

# revision identifiers, used by Alembic.
revision = 'b0eff40d2b66'
down_revision = 'c24e73c181e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_device', sa.Column('state', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene_device', 'state')
    ### end Alembic commands ###
